### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by wraseman** [walkerjeffd/phd-wirm-client#1]
Hi Jeff, 

The links to WIRM (http://wirm.walkerenvres.com and http://wirm.walkerjeff.com) appear to be broken. Where can I access WIRM?

Thank,
Billy

**Comment by walkerjeffd** [comment]
Thanks for the heads up, Billy! 

When I switched from walkerjeff.com to walkerenvres.com a couple years ago, I didn't do a good job configuring the new server to run Django, which does the server-side part of WIRM. 

But I think I got everything set now, should be up and running at: https://wirm.walkerenvres.com/

Jeff
